package tests

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"Game-Developers-World/seed/internal/generators"
)

func TestGenerationSafety(t *testing.T) {
	tmpDir := t.TempDir()

	const component = "type: component\nname: Position\nnamespace: Core\nfields:\n  - name: x\n    type: float\n"

	t.Run("generated files carry a provenance header naming their source", func(t *testing.T) {
		dir := filepath.Join(tmpDir, "provenance")
		defer inDir(t, dir)()
		writeModel(t, dir, "Component", "Position", component)

		if err := generators.Sync(); err != nil {
			t.Fatal(err)
		}
		data, err := os.ReadFile(filepath.Join(dir, "Include", "Core", "Position.hpp"))
		if err != nil {
			t.Fatal(err)
		}
		if !strings.Contains(string(data), "Code generated by seed") ||
			!strings.Contains(string(data), "Models/Component/Position.yaml") ||
			!strings.Contains(string(data), "DO NOT EDIT") {
			t.Fatalf("expected a provenance header, got:\n%s", data)
		}
	})

	t.Run("a user-owned System .cpp is never overwritten, but gets a one-time header", func(t *testing.T) {
		dir := filepath.Join(tmpDir, "user-owned")
		defer inDir(t, dir)()
		writeModel(t, dir, "System", "Gravity", "type: system\nname: Gravity\nnamespace: Core\npriority: 0\n")

		if err := generators.Sync(); err != nil {
			t.Fatal(err)
		}
		cppPath := filepath.Join(dir, "Src", "Game", "Gravity.cpp")
		original, err := os.ReadFile(cppPath)
		if err != nil {
			t.Fatal(err)
		}
		if !strings.Contains(string(original), "Generated once by seed") {
			t.Fatalf("expected a one-time ownership header, got:\n%s", original)
		}

		modified := string(original) + "\n// my custom logic\n"
		if err := os.WriteFile(cppPath, []byte(modified), 0644); err != nil {
			t.Fatal(err)
		}

		if err := generators.Sync(); err != nil {
			t.Fatal(err)
		}
		after, err := os.ReadFile(cppPath)
		if err != nil {
			t.Fatal(err)
		}
		if string(after) != modified {
			t.Fatalf("expected the user-owned .cpp to survive re-sync untouched, got:\n%s", after)
		}
	})

	t.Run("re-syncing unchanged models does not touch file mtimes", func(t *testing.T) {
		dir := filepath.Join(tmpDir, "mtime")
		defer inDir(t, dir)()
		writeModel(t, dir, "Component", "Position", component)

		if err := generators.Sync(); err != nil {
			t.Fatal(err)
		}
		hppPath := filepath.Join(dir, "Include", "Core", "Position.hpp")
		info1, err := os.Stat(hppPath)
		if err != nil {
			t.Fatal(err)
		}

		// Sleep past typical filesystem mtime granularity so a real
		// rewrite (a bug regression) would be detectable.
		time.Sleep(1100 * time.Millisecond)

		if err := generators.Sync(); err != nil {
			t.Fatal(err)
		}
		info2, err := os.Stat(hppPath)
		if err != nil {
			t.Fatal(err)
		}
		if !info1.ModTime().Equal(info2.ModTime()) {
			t.Fatalf("expected mtime to be unchanged across an identical re-sync: %v vs %v", info1.ModTime(), info2.ModTime())
		}
	})

	t.Run("generation is deterministic across repeated runs", func(t *testing.T) {
		dir := filepath.Join(tmpDir, "determinism")
		defer inDir(t, dir)()
		writeModel(t, dir, "Component", "Position", component)
		writeModel(t, dir, "Component", "Velocity", "type: component\nname: Velocity\nnamespace: Core\nfields:\n  - name: dx\n    type: float\n")
		writeModel(t, dir, "Trait", "Movable", "type: trait\nname: Movable\nnamespace: Core\ncomponents:\n  - Position\n  - Velocity\n")

		if err := generators.Sync(); err != nil {
			t.Fatal(err)
		}
		snapshot := snapshotDir(t, filepath.Join(dir, "Include"))

		if err := os.RemoveAll(filepath.Join(dir, "Include")); err != nil {
			t.Fatal(err)
		}
		if err := generators.Sync(); err != nil {
			t.Fatal(err)
		}
		snapshot2 := snapshotDir(t, filepath.Join(dir, "Include"))

		if len(snapshot) != len(snapshot2) {
			t.Fatalf("expected the same set of files, got %d vs %d", len(snapshot), len(snapshot2))
		}
		for path, content := range snapshot {
			if snapshot2[path] != content {
				t.Fatalf("expected identical content for %s across repeated syncs", path)
			}
		}
	})

	t.Run("SyncPlan (dry-run) reports changes without writing anything", func(t *testing.T) {
		dir := filepath.Join(tmpDir, "dry-run")
		defer inDir(t, dir)()
		writeModel(t, dir, "Component", "Position", component)

		changes, err := generators.SyncPlan()
		if err != nil {
			t.Fatal(err)
		}
		if _, statErr := os.Stat(filepath.Join(dir, "Include")); !os.IsNotExist(statErr) {
			t.Fatal("expected SyncPlan to write nothing to disk")
		}
		found := false
		for _, c := range changes {
			if strings.HasSuffix(c.Path, "Position.hpp") && c.Action == generators.ActionCreate {
				found = true
			}
		}
		if !found {
			t.Fatalf("expected a 'create' entry for Position.hpp, got: %+v", changes)
		}

		// Now actually sync, modify the model, and confirm the plan
		// reports an update with a non-empty diff — and still writes
		// nothing.
		if err := generators.Sync(); err != nil {
			t.Fatal(err)
		}
		writeModel(t, dir, "Component", "Position", "type: component\nname: Position\nnamespace: Core\nfields:\n  - name: x\n    type: double\n")

		before, err := os.ReadFile(filepath.Join(dir, "Include", "Core", "Position.hpp"))
		if err != nil {
			t.Fatal(err)
		}

		changes, err = generators.SyncPlan()
		if err != nil {
			t.Fatal(err)
		}
		var updateDiff string
		for _, c := range changes {
			if strings.HasSuffix(c.Path, "Position.hpp") {
				if c.Action != generators.ActionUpdate {
					t.Fatalf("expected an update action, got %v", c.Action)
				}
				updateDiff = c.Diff
			}
		}
		if updateDiff == "" || !strings.Contains(updateDiff, "double") {
			t.Fatalf("expected a diff mentioning the new type, got: %q", updateDiff)
		}

		after, err := os.ReadFile(filepath.Join(dir, "Include", "Core", "Position.hpp"))
		if err != nil {
			t.Fatal(err)
		}
		if string(before) != string(after) {
			t.Fatal("expected SyncPlan to leave the existing generated file untouched")
		}
	})

	t.Run("Sync still refuses to generate partial output on semantic errors", func(t *testing.T) {
		dir := filepath.Join(tmpDir, "atomic-abort")
		defer inDir(t, dir)()
		writeModel(t, dir, "Trait", "Movable", "type: trait\nname: Movable\nnamespace: Core\ncomponents:\n  - DoesNotExist\n")

		if err := generators.Sync(); err == nil {
			t.Fatal("expected Sync to fail")
		}
		if _, statErr := os.Stat(filepath.Join(dir, "Include")); !os.IsNotExist(statErr) {
			t.Fatal("expected no Include/ output when Sync aborts")
		}
	})
}

func snapshotDir(t *testing.T, root string) map[string]string {
	t.Helper()
	out := map[string]string{}
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() {
			return err
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		out[rel] = string(data)
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}
	return out
}
