package generators

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

// SeedVersion is the tool version stamped into generated-file provenance
// headers (§8's "generated-file headers and provenance metadata"). Kept
// here rather than importing the cobra root command's version (which
// would make internal/generators depend on internal/commands, inverting
// the actual dependency direction) — both currently read "0.1.0"; keep
// them in sync by hand until there's a single shared version source.
const SeedVersion = "0.1.0"

// generatedFileHeader is prepended to every fully-generated file (never to
// a user-owned file like a System's .cpp implementation). It is the
// concrete marker for "distinguish fully generated files from user-owned
// files": a file starting with this exact comment is safe to regenerate
// and never hand-edited; a file without it is not. sourcePath is the
// Models/ YAML file the output was generated from — provenance, not just
// a "don't edit" warning. Deliberately excludes a timestamp: a build
// timestamp would make two syncs of the same models produce
// byte-different output, breaking "reproducible across machines and
// repeated runs" for no benefit a content diff doesn't already give.
func generatedFileHeader(sourcePath string) string {
	return fmt.Sprintf("// Code generated by seed v%s from %s. DO NOT EDIT.\n\n", SeedVersion, filepath.ToSlash(sourcePath))
}

// userOwnedFileHeader is prepended once, only when a user-owned file
// (a System's .cpp implementation) is first created. It never appears
// again on subsequent syncs — writeCpp already skips existing files
// entirely — so it's a one-time orientation note, not a marker checked
// programmatically the way generatedFileHeader's presence could be.
func userOwnedFileHeader(sourcePath string) string {
	return fmt.Sprintf("// Generated once by seed from %s; edit freely below.\n// seed will not overwrite this file again — delete it to regenerate.\n\n",
		filepath.ToSlash(sourcePath))
}

// formatBuffer pipes content through clang-format (if installed) and
// returns the formatted result, or content unchanged if clang-format
// isn't available. Formatting happens here — in memory, before a sink
// ever sees the bytes — rather than by running `clang-format -i` on the
// file after writing (the previous approach): comparing an unformatted
// rendered buffer against an already-formatted on-disk file would make
// diskSink's "skip an identical write" check and dryRunSink's diff both
// see spurious formatting-only differences on every single sync, even
// when nothing meaningful changed.
func formatBuffer(content []byte) []byte {
	path, err := exec.LookPath("clang-format")
	if err != nil {
		return content
	}
	cmd := exec.Command(path)
	cmd.Stdin = bytes.NewReader(content)
	var out bytes.Buffer
	cmd.Stdout = &out
	if err := cmd.Run(); err != nil {
		return content
	}
	return out.Bytes()
}

// prependHeader adds header before body without re-running it through
// clang-format. Headers are added after formatBuffer(body), not before,
// specifically because clang-format's line-wrapping would otherwise
// reflow a long header comment (source paths vary in length) across two
// lines in a way that isn't stable to depend on for comparisons —
// dryRunSink's diff and diskSink's identical-content check both need the
// same bytes every time a given header+body pair is produced.
func prependHeader(header string, body []byte) []byte {
	out := make([]byte, 0, len(header)+len(body))
	out = append(out, header...)
	out = append(out, body...)
	return out
}

// atomicWriteFile writes content to path by first writing to a temporary
// file in the same directory, then renaming it into place. Rename is
// atomic on the same filesystem (POSIX and Windows both guarantee this for
// a same-volume rename), so a process interrupted mid-write, a full disk,
// or a template panic never leaves a truncated or half-written file at
// path — the previous version stays intact until the new one is complete
// and only then swapped in one step. This directly satisfies "generate
// files atomically so template failures cannot leave partial output."
func atomicWriteFile(path string, content []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".seed-tmp-*")
	if err != nil {
		return fmt.Errorf("creating temp file: %w", err)
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath) // no-op once the rename below succeeds

	if _, err := tmp.Write(content); err != nil {
		tmp.Close()
		return fmt.Errorf("writing temp file: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("closing temp file: %w", err)
	}
	if err := os.Chmod(tmpPath, perm); err != nil {
		return fmt.Errorf("setting permissions: %w", err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("renaming into place: %w", err)
	}
	return nil
}

// FileAction is what happened (or, in a dry run, would happen) to one
// output file during Sync.
type FileAction string

const (
	ActionCreate    FileAction = "create"
	ActionUpdate    FileAction = "update"
	ActionUnchanged FileAction = "unchanged"
)

// FileChange is one entry in a sync plan: what would happen to Path, and
// (for an update to an existing generated file) a line-level diff against
// its current content.
type FileChange struct {
	Path   string
	Action FileAction
	Diff   string // only set for ActionUpdate
}

// writeSink is where a rendered file's bytes go: either actually written
// to disk (diskSink) or only compared against what's already there
// (dryRunSink, recording a FileChange and never touching the filesystem).
// Every generation call site in this package goes through a sink instead
// of calling os.Create/os.WriteFile directly, which is what makes
// "seed sync --dry-run" a read-only pass over the exact same code path
// real generation uses — not a separate, divergent implementation that
// could drift from what a real sync actually does.
type writeSink interface {
	write(path string, content []byte, perm os.FileMode) error
}

type diskSink struct{}

func (diskSink) write(path string, content []byte, perm os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("creating directory: %w", err)
	}
	// Skip the write (and the mtime bump that would otherwise make
	// GetSyncStatus/checkOrphanedFiles see a false "stale" result) when
	// content is byte-identical to what's already on disk.
	if existing, err := os.ReadFile(path); err == nil && bytes.Equal(existing, content) {
		return nil
	}
	return atomicWriteFile(path, content, perm)
}

type dryRunSink struct {
	changes *[]FileChange
}

func (s dryRunSink) write(path string, content []byte, perm os.FileMode) error {
	existing, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			*s.changes = append(*s.changes, FileChange{Path: path, Action: ActionCreate})
			return nil
		}
		return fmt.Errorf("reading existing %s: %w", path, err)
	}
	if bytes.Equal(existing, content) {
		*s.changes = append(*s.changes, FileChange{Path: path, Action: ActionUnchanged})
		return nil
	}
	*s.changes = append(*s.changes, FileChange{
		Path:   path,
		Action: ActionUpdate,
		Diff:   unifiedDiff(string(existing), string(content), 3),
	})
	return nil
}

// writeOnceSink wraps another sink but refuses to touch a path that
// already exists — the mechanism behind "preserve manual system
// implementations across regeneration". A dry run still reports what
// *would* happen if the file didn't already exist (nothing) accurately,
// since checking existence is itself side-effect-free.
type writeOnceSink struct {
	inner writeSink
}

func (s writeOnceSink) write(path string, content []byte, perm os.FileMode) error {
	if _, err := os.Stat(path); err == nil {
		return nil
	}
	return s.inner.write(path, content, perm)
}
